using AutoMapper;
using DTO;
using Entities;

public class MappingProfile : Profile
{
    public MappingProfile()
    {
        // 1. Inbound Request Mappings (DTO -> Entity)
        CreateMap<WorkRequestDto, WorkRequest>()
            // Map the differing property names. AutoMapper handles the underlying Enum mapping automatically.
            .ForMember(dest => dest.Priority, opt => opt.MapFrom(src => src.PriorityDto))
            .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.StatusDto))

            // Ignore properties that are auto-generated by the Entity class defaults or Database
            .ForMember(dest => dest.Id, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedDate, opt => opt.Ignore())
            .ForMember(dest => dest.UpdatedDate, opt => opt.Ignore())
            .ForMember(dest => dest.Notes, opt => opt.Ignore());

        // 2. Outbound Response Mappings (Entity -> DTO)
        CreateMap<WorkRequest, WorkRequestDto>()
            // Map the differing property names back to the DTO
            .ForMember(dest => dest.PriorityDto, opt => opt.MapFrom(src => src.Priority))
            .ForMember(dest => dest.StatusDto, opt => opt.MapFrom(src => src.Status));

        // 3. Note Mappings
        CreateMap<NoteDto, Note>()
            // Ignore navigational and auto-generated properties on inbound mapping
            .ForMember(dest => dest.Id, opt => opt.Ignore())
            .ForMember(dest => dest.WorkRequestId, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedDate, opt => opt.Ignore())
            .ForMember(dest => dest.WorkRequest, opt => opt.Ignore());

        CreateMap<Note, NoteDto>();
    }
}